In [1]:

import numpy as np
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2 , np.nan,4],
    "B": [ 5.1, np.nan,6.6,8.8],
    "C": ["foo","zoo","bar", np.nan],
    'D':[6,7,8,9]
})
print(df)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  NaN  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  NaN  9

In [4]:
df.dropna(axis=1)

   D
0  6
1  7
2  8
3  9

In [7]:
df.fillna(1)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  1.0  zoo  7
2  1.0  6.6  bar  8
3  4.0  8.8    1  9

In [9]:
df

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  NaN  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  NaN  9

In [11]:
df.ffill(axis=1)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  2.0  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  8.8  9

In [13]:
df.bfill(axis=1)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  zoo  zoo  7
2  6.6  6.6  bar  8
3  4.0  8.8    9  9

In [15]:
df1=pd.read_csv('sp500.csv')
df1

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials     NaN   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [16]:
df1.ffill(axis=0)

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   2.41
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   70.25   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]