In [1]:
import pandas as pd
import numpy as np

mp5=np.arange(25,50).reshape(5,5)
print(mp5)
df1=pd.DataFrame(mp5,index=['a','b','c','d','e'],columns=['A','B','C','D','E'])
print(df1)
print('hello world how are you ')

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
    A   B   C   D   E
a  25  26  27  28  29
b  30  31  32  33  34
c  35  36  37  38  39
d  40  41  42  43  44
e  45  46  47  48  49
hello world how are you

In [2]:
l2=[[1,2,3],[44,55,66],[7,8,9]]
df2=pd.DataFrame(l2,index=['r1','r2','r3'],columns=['c1','c2','c3'])
print(df2)

    c1  c2  c3
r1   1   2   3
r2  44  55  66
r3   7   8   9

In [3]:
ld1=[{'Name':'Amit','Age':22,'City':'Delhi'},
     {'Name':'Sumit','Age':25,'City':'Mumbai'},
     {'Name':'Rohit','Age':24,'City':'Chennai'}]

df3=pd.DataFrame(ld1)
print(df3)

    Name  Age     City
0   Amit   22    Delhi
1  Sumit   25   Mumbai
2  Rohit   24  Chennai

In [4]:
dl1={'Name':['Amit','Sumit','Rohit'],
     'Age':[22,25,24],
     'City':['Delhi','Mumbai','Chennai']}
df4=pd.DataFrame(dl1)
print(df4)

    Name  Age     City
0   Amit   22    Delhi
1  Sumit   25   Mumbai
2  Rohit   24  Chennai

In [5]:
df4=pd.read_csv(r'/Users/algo trading 2026/batch 37/11_pandas/sp500.csv')
print(df4)

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [6]:
!pip install lxml

Requirement already satisfied: lxml in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (6.1.1)

In [7]:
!pip install --upgrade certifi

Requirement already satisfied: certifi in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (2026.5.20)

In [8]:
import os, certifi
# Set SSL certificate path for macOS
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

In [13]:
!pip install requests

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: certifi>=2023.5.7 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests) (2026.5.20)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, idna, charset_normalizer, requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [requests]
Successfully installed charset_normalizer-3.4.7 idna-3.18 requests-2.34.2 urllib3-2.7.0

In [18]:
import requests

resp = requests.get("https://www.screener.in/company/NIFTY/", headers={"User-Agent": "Mozilla/5.0"})
resp.text

'\n<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n\n    \n    <title>\n  Nifty 50 value and PE ratio | Constituents of Nifty 50\n - Screener</title>\n    \n\n    <!-- plausible -->\n    <script defer\n            event-user="unregistered"\n            \n            \n            data-domain="screener.in"\n            src="https://plausible.screener.in/js/script.pageview-props.tagged-events.js"></script>\n    <script>window.plausible = window.plausible || function () { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>\n\n    <script src="https://rybbit.screener.in/api/script.js"\n            data-site-id="5494427e1dc0"\n            defer></script>\n\n    <!-- FONT -->\n    <link rel="stylesheet" href="https://cdn-static.screener.in/inter/inter.bccd7465af74.css?v=2" />\n    <link rel="stylesheet" href="https://cdn-static.screener.in/fontello/css/fontello.835ae8880a8b.css?v=2" />\n\n    <!-- CSS -->\n    <link rel="stylesheet" href="https://cdn-static.screener.in/css/normalize.a2444750a947.css" media="all">\n    <link rel="stylesheet" href="https://cdn-static.screener.in/css/skeleton.e1c50fcb2cfe.css" media="all">\n    <link rel="stylesheet" href="https://cdn-static.screener.in/css/custom.face9eb25802.css" media="all">\n\n    \n    \n    \n  \n\n  \n  \n  \n\n  <style>\n  .persistent-messages:has(.show-on-company-page),\n  .show-on-company-page.hidden {\n    display: block;\n  }\n\n  tr[data-row-company-id="1272594"] {\n    font-weight: 500;\n  }\n\n  tr[data-row-company-id="1272594"] a {\n    color: var(--ink-900);\n  }\n\n  :target {\n    scroll-margin-top: 90px;\n  }\n\n  @supports not (scroll-margin-top: 90px) {\n    :target {\n      padding-top: 108px;\n    }\n  }\n\n  @media (min-width: 992px) {\n    nav {\n      margin-bottom: 0;\n    }\n\n    .company-nav {\n      top: 50px;\n      margin-bottom: 24px;\n    }\n  }\n  </style>\n\n\n    <meta name="author" content="Mittal Analytics Private Limited">\n\n    <!-- PWA manifest -->\n    <meta name="theme-color"\n          content="#fff"\n          media="(prefers-color-scheme: light)">\n    <meta name="theme-color"\n          content="#222530"\n          media="(prefers-color-scheme: dark)">\n    <link rel="manifest" href="/static/manifest.json">\n\n    <!-- favicons -->\n    <link rel="apple-touch-icon"\n          sizes="180x180"\n          href="https://cdn-static.screener.in/favicon/apple-touch-icon.b6e5f24bf7d3.png">\n    <link rel="icon"\n          type="image/png"\n          sizes="32x32"\n          href="https://cdn-static.screener.in/favicon/favicon-32x32.00205914303a.png">\n    <link rel="icon"\n          type="image/png"\n          sizes="16x16"\n          href="https://cdn-static.screener.in/favicon/favicon-16x16.2b35594b2f33.png">\n    <link rel="mask-icon"\n          href="https://cdn-static.screener.in/favicon/safari-pinned-tab.adbe3ed3c5ad.svg"\n          color="#8ED443">\n    <meta name="msapplication-TileColor" content="#da532c">\n  </head>\n\n  <body class="light flex-column">\n    \n      <nav class="u-full-width no-print">\n        <div id="mobile-search"><div class="has-addon left-addon dropdown-typeahead">\n  <i class="addon icon-search"></i>\n  <input\n    aria-label="Search for a company"\n    type="search"\n    autocomplete="off"\n    spellcheck="false"\n    placeholder="Search for a company"\n    class="u-full-width"\n    \n    data-company-search="true">\n</div>\n</div>\n\n<ul class="bottom-menu-bar hide-from-tablet-landscape">\n  \n    <li class="">\n      <a href="/">\n        <i class="icon-home"></i>\n        <br>\n        Home\n      </a>\n    </li>\n  \n\n  <li class="">\n    <a href="/explore/">\n      <i class="icon-screens"></i>\n      <br>\n      Screens\n    </a>\n  </li>\n\n  <li>\n    <button type="button"\n            onclick="MobileMenu.toggleSearch(this)"\n            class="search-button"\n            title="Search">\n      <i class="icon-search" style="font-size: 18px"></i>\n    </button>\n  </li>\n\n  <li>\n    <button class="button-plain" onclick="Modal.showInModal(\'#nav-tools-menu\')">\n      <i class="icon-tools"></i>\n      <br>\n      Tools\n    </button>\n  </li>\n\n  \n    <li class="">\n      <a href="/register/?">\n        <i class="icon-user-plus"></i>\n        <br>\n        Login\n      </a>\n    </li>\n  \n</ul>\n\n        <div class="top-nav-holder">\n          <div class="container">\n\n\n\n<div class="layer-holder top-navigation">\n  <div class="layer flex flex-space-between"\n       style="align-items: center;\n              height: 50px">\n    <div class="flex" style="align-items: center">\n      <a href="/" class="logo-holder">\n        <img alt="Screener Logo"\n             class="logo"\n             src="https://cdn-static.screener.in/img/logo-black.f44abb4998d1.svg" />\n      </a>\n\n      <div class="desktop-links" style="margin-left: 48px">\n        <a href="/">\n          \n            Home\n          \n        </a>\n        <a href="/explore/">Screens</a>\n        <div class="dropdown-menu">\n          <button class="button-plain"\n                  type="button"\n                  onclick="Utils.toggleDropdown(event)">\n            Tools\n            <i class="icon-down"></i>\n          </button>\n          <ul class="dropdown-content flex-column tools-menu"\n              style="width: 350px"\n              id="nav-tools-menu">\n            <li>\n              <a href="/screen/new/"\n                 class="flex flex-align-center flex-gap-16">\n                <div class="bg-stripes square-56">\n                  <img src="https://cdn-static.screener.in/icons/screens.e960a5daedf9.svg" alt="Create a stock screen">\n                </div>\n                <div>\n                  <div class="font-weight-500 font-size-14">Create a stock screen</div>\n                  <div class="sub font-size-13">Run queries on 10 years of financial data</div>\n                </div>\n              </a>\n            </li>\n            <li class="flex flex-align-center no-hover" style="padding: 4px 0;">\n              <div class="button button-primary premium-indicator flex flex-align-center">\n                <img src="https://cdn-static.screener.in/icons/crown.fb0d2413ee43.svg"\n                     alt="Premium icon"\n                     style="margin-right: 8px">\n                <span>Premium features</span>\n              </div>\n              <hr class="flex-grow" style="padding: 0; margin: 0;">\n            </li>\n            \n              <li>\n                <a href="/ai/"\n                   class="flex flex-align-center flex-gap-16">\n                  <div class="bg-stripes square-56">\n                    <img src="https://cdn-static.screener.in/icons/ai.970ef1d1cabb.svg" alt="Screener AI">\n                  </div>\n                  <div>\n                    <div class="font-weight-500 font-size-14">Screener AI</div>\n                    <div class="sub font-size-13">Extract valuable insights from hundreds of company documents.</div>\n                  </div>\n                </a>\n              </li>\n            \n            <li>\n              <a href="/hs/" class="flex flex-align-center flex-gap-16">\n                <div class="bg-stripes square-56">\n                  <img src="https://cdn-static.screener.in/icons/export.d623f0029933.svg" alt="Commodity Prices">\n                </div>\n                <div>\n                  <div class="font-weight-500 font-size-14">Commodity Prices</div>\n                  <div class="sub font-size-13">Analyze price trends for 10,000+ commodities over the past 10 years.</div>\n                </div>\n              </a>\n            </li>\n            <li>\n              <a href="/people/"\n                 class="flex flex-align-center flex-gap-16">\n                <div class="bg-stripes square-56">\n                  <img src="https://cdn-static.screener.in/icons/shares.10acc20cb936.svg"\n                       alt="Search shareholders by name">\n                </div>\n                <div>\n                  <div class="font-weight-500 font-size-14">Search shareholders</div>\n                  <div class="sub font-size-13">Find all companies where a person owns more than 1% of shares.</div>\n                </div>\n              </a>\n            </li>\n            <li>\n              <a href="/announcements/"\n                 class="flex flex-align-center flex-gap-16">\n                <div class="bg-stripes square-56">\n                  <img src="https://cdn-static.screener.in/icons/loudspeaker.88769927f6eb.svg" alt="Loudspeaker">\n                </div>\n                <div>\n                  <div class="font-weight-500 font-size-14">Company Announcements</div>\n                  <div class="sub font-size-13">\n                    Stay updated. Search, filter and set alerts for the newest disclosures and developments.\n                  </div>\n                </div>\n              </a>\n            </li>\n            \n              <li style="padding: 16px;">\n                <a href="/premium/?driver=top-nav-tools"\n                   class="button button-primary text-align-center"\n                   style="color: var(--white);\n                          padding: 10px 24px">Upgrade to premium</a>\n              </li>\n            \n          </ul>\n        </div>\n      </div>\n    </div>\n\n    <div class="show-from-tablet-landscape flex flex-gap-16"\n         style="justify-content: flex-end;\n                flex: 1 1 400px">\n      <div class="search" id="desktop-search"><div class="has-addon left-addon dropdown-typeahead">\n  <i class="addon icon-search"></i>\n  <input\n    aria-label="Search for a company"\n    type="search"\n    autocomplete="off"\n    spellcheck="false"\n    placeholder="Search for a company"\n    class="u-full-width"\n    \n    data-company-search="true">\n</div>\n</div>\n\n      \n        <div class="flex flex-gap-8" style="margin: 4px">\n          <a class="button account"\n             href="/login/?">\n            <i class="icon-user-line blue-icon"></i>\n            Login\n          </a>\n          <a class="button account button-secondary"\n             href="/register/?">Get free account</a>\n        </div>\n      \n    </div>\n  </div>\n</div>\n</div>\n        </div>\n      </nav>\n    \n\n    \n  <div class="bg-base company-nav">\n    <div class="flex flex-space-between container hide-from-tablet-landscape">\n      <h1 class="h2 shrink-text" style="margin: 0.5em 0">Nifty 50</h1>\n      <button type="button"\n        class="a sub plausible-event-name=Notebook plausible-event-user=unregistered"\n        onclick="Modal.openInModal(event)"\n        data-url="/notebook/1272594/"\n        data-title="Nifty 50"\n        data-is-right-modal="true"\n        title="View Notebook">\n  \n    <i class="icon-book-open"></i>\n  \n  <span class="show-from-tablet-landscape">Notebook</span>\n</button>\n\n    </div>\n\n    <div class="sub-nav-holder">\n      <div class="sub-nav">\n        <div class="sub-nav-tabs">\n          <a href="#top">\n            <span class="shrink-text show-from-tablet-landscape">Nifty 50</span>\n            <span class="hide-from-tablet-landscape">Summary</span>\n          </a>\n          <a href="#chart">Chart</a>\n          <a href="#constituents">Constituents</a>\n        </div>\n        <div class="sub-nav-actions show-from-tablet-landscape"><button type="button"\n        class="a sub plausible-event-name=Notebook plausible-event-user=unregistered"\n        onclick="Modal.openInModal(event)"\n        data-url="/notebook/1272594/"\n        data-title="Nifty 50"\n        data-is-right-modal="true"\n        title="View Notebook">\n  \n    <i class="icon-book-open"></i>\n  \n  <span class="show-from-tablet-landscape">Notebook</span>\n</button>\n</div>\n      </div>\n    </div>\n  </div>\n\n\n    \n      <main class="flex-grow container">\n        \n\n\n  \n\n\n\n\n\n\n        \n        <div class="breadcrumb hidden-if-empty"></div>\n        \n\n        \n  <div data-company-id="1272594"\n       \n       \n       \n       id="company-info"></div>\n\n  <div class="card card-large" id="top">\n    <div class="flex flex-space-between flex-gap-8">\n      <div class="flex-row flex-wrap flex-align-center flex-grow"\n           style="flex-basis: 300px">\n        <h1 class="margin-0 show-from-tablet-landscape">Nifty 50</h1>\n        <div class="ink-600 show-from-tablet-landscape" style="opacity: 0.5;">\n          <i class="icon-dot"></i>\n        </div>\n        <div class="font-size-18 strong line-height-14">\n          <div class="flex flex-align-center">\n            <span>₹ 23,623</span>\n            \n              <span class="font-size-12 up margin-left-4">\n                <i class="icon-circle-up"></i>\n                1.99%\n              </span>\n            \n          </div>\n          <div class="ink-600 font-size-11 font-weight-500">\n            \n              12 Jun\n              \n                - close price\n              \n            \n          </div>\n        </div>\n      </div>\n\n      <form method="post" class="flex margin-0" style="align-items: center">\n        <input type="hidden" name="csrfmiddlewaretoken" value="ayVrdpaYkc4c8feuat5KTLtxzmQIMiZdgyyTVuCFMtmf0yTvlVWIi6pfogd6sBVf">\n        <input type="hidden" name="next" value="/company/NIFTY/">\n\n        \n\n        <div class="flex dropdown-filter">\n          \n            <button class="button-primary "\n                    formaction="/api/company/1272594/add/">\n              <i class="icon-plus"></i> Follow\n            </button>\n          \n\n          \n        </div>\n      </form>\n    </div>\n\n    \n    <div class="company-links show-from-tablet-landscape"\n         style="font-weight: 500;\n                margin-top: 8px">\n      \n\n      \n\n      \n    </div>\n    \n\n    <div class="company-info">\n      \n      <div class="company-profile">\n        <div class="flex flex-column" style="flex: 1 1;">\n          <div class="title">About</div>\n          <div class="sub show-more-box about" style="flex-basis: 100px"><p>The NIFTY 50 is a benchmark Indian stock market index that represents the weighted average of 50 of the largest Indian companies listed on the National Stock Exchange. Nifty 50 is owned and managed by NSE Indices, which is a wholly owned subsidiary of the NSE Strategic Investment Corporation Limited.</p></div>\n\n          \n            <div class="smaller normal-case font-weight-400 sub show-from-tablet-landscape">\n              <div>\n                [\n                <a href="/wiki/company/1272594/about/edit/">edit about</a>\n                ]\n              </div>\n              <div class="margin-top-16">\n                [\n                <a href="/wiki/company/1272594/commentary/edit/">add key points</a>\n                ]\n              </div>\n            </div>\n          \n        </div>\n\n        <div class="company-links hide-from-tablet-landscape margin-top-20"\n             style="font-weight: 500">\n          \n\n          \n\n          \n        </div>\n      </div>\n      \n\n      <div class="company-ratios">\n        <ul id="top-ratios">\n          \n\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        Market Cap\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        ₹\n        <span class="number">1,90,65,354</span>\n        \n          Cr.\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        Current Price\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        ₹\n        <span class="number">23,623</span>\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        High / Low\n      \n    </span>\n\n    \n      <span class="nowrap value">₹ <span class="number">26,373</span> / <span class="number">22,183</span></span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        P/E\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        \n        <span class="number">20.4</span>\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        Price to Book value\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        \n        <span class="number">3.11</span>\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        Dividend Yield\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        \n        <span class="number">1.23</span>\n        \n          %\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        CAGR 1Yr\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        \n        <span class="number">-6.02</span>\n        \n          %\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        CAGR 5Yr\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        \n        <span class="number">8.37</span>\n        \n          %\n        \n      </span>\n    \n  </li>\n\n  <li class="flex flex-space-between" data-source="default">\n    <span class="name">\n      \n        CAGR 10Yr\n      \n    </span>\n\n    \n      <span class="nowrap value">\n        \n        <span class="number">11.3</span>\n        \n          %\n        \n      </span>\n    \n  </li>\n\n\n\n\n\n\n        </ul>\n\n        <div style="margin-top: 32px;">\n          <label for="quick-ratio-search">Add ratio to table</label>\n\n          <div class="flex-row flex-space-between flex-baseline flex-gap-16">\n            <div class="dropdown-typeahead flex-grow" style="max-width: 480px;">\n              <input id="quick-ratio-search"\n                     type="text"\n                     placeholder="eg. Promoter holding"\n                     style="width: 100%">\n            </div>\n\n            \n            <a href="/user/quick_ratios/?next=/company/NIFTY/"\n               class="smaller">\n              <i class="icon-pencil"></i>\n              <span class="upper font-weight-500 letter-spacing">Edit ratios</span>\n            </a>\n          </div>\n        </div>\n      </div>\n    </div>\n  </div>\n\n  \n  <section id="chart" class="card card-large" style="margin-bottom: 2.5rem">\n    <div id="chart-menu"\n     class="flex flex-space-between flex-wrap"\n     style="margin-bottom: 16px">\n  <div class="options" id="company-chart-days">\n    <button name="days"\n            value="30"\n            onclick="CompanyChart.setActive(event)"\n            type="button">1M</button>\n    <button name="days"\n            value="180"\n            onclick="CompanyChart.setActive(event)"\n            type="button">6M</button>\n    <button name="days"\n            value="365"\n            onclick="CompanyChart.setActive(event)"\n            type="button">1Yr</button>\n    <button name="days"\n            value="1095"\n            onclick="CompanyChart.setActive(event)"\n            type="button">3Yr</button>\n    <button name="days"\n            value="1825"\n            onclick="CompanyChart.setActive(event)"\n            type="button">5Yr</button>\n    <button name="days"\n            value="3652"\n            onclick="CompanyChart.setActive(event)"\n            type="button">10Yr</button>\n    <button name="days"\n            value="10000"\n            onclick="CompanyChart.setActive(event)"\n            type="button">Max</button>\n  </

In [20]:
import requests
import pandas as pd
from io import StringIO

url = "https://www.screener.in/company/NIFTY/"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}

resp = requests.get(url, headers=headers, timeout=10)
resp.raise_for_status()

tables = pd.read_html(StringIO(resp.text))   # returns a LIST of DataFrames
tables[0]

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1293.00,22.47,1749756.77,0.46,20589.00,-12.55,294059.00,12.50,10.26
1,2.,HDFC Bank,772.45,15.64,1189391.41,1.68,21074.22,8.05,87182.50,0.46,7.04
2,3.,Bharti Airtel,1822.50,38.67,1110500.17,0.88,9247.40,-16.49,55383.20,15.68,18.50
3,4.,ICICI Bank,1340.80,17.74,961620.51,0.82,15680.64,9.28,49593.75,2.49,7.20
4,5.,SBI,1017.15,11.27,938892.27,1.71,20507.98,0.22,131080.12,3.34,6.13
5,6.,TCS,2161.40,14.95,782013.44,2.96,13784.00,12.22,70698.00,9.65,63.03
6,7.,Bajaj Finance,918.30,29.76,571729.38,0.59,5553.30,21.99,21605.79,18.10,10.82
7,8.,Larsen & Toubro,4049.30,33.95,557074.02,0.94,6133.06,2.11,82762.16,11.25,14.57
8,9.,Hind. Unilever,2168.80,33.46,509579.35,1.89,2994.00,8.62,16351.00,7.64,28.42
9,10.,Infosys,1116.40,15.06,452952.05,4.30,8509.00,20.87,46402.00,13.38,39.95
10,11.,Sun Pharma.Inds.,1807.70,34.76,433727.78,0.89,2709.66,13.58,14611.79,12.76,20.53
11,12.,Axis Bank,1356.30,15.99,421816.93,0.07,7642.08,1.71,34170.99,5.30,6.24
12,13.,Maruti Suzuki,13366.00,28.63,420230.48,1.01,3659.00,-6.45,52462.50,28.21,19.02
13,14.,Adani Ports,1812.90,32.22,417684.75,0.41,3308.30,11.43,10737.56,26.50,14.12
14,15.,Kotak Mah. Bank,403.30,21.09,401142.71,0.12,5423.15,4.53,17827.36,6.29,6.93
15,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
16,16.,Adani Enterp.,2921.60,NaN,380072.41,0.04,-166.79,-121.16,32439.31,20.30,5.80
17,17.,M & M,3042.90,21.40,378393.39,1.08,5259.91,48.85,54981.91,29.07,15.45
18,18.,Titan Company,4184.00,72.15,371449.73,0.26,1179.00,31.00,26920.00,80.48,25.80
19,19.,ITC,285.10,17.09,357215.14,5.09,5469.74,5.30,17824.68,-5.01,38.93
20,20.,NTPC,353.90,12.69,343165.01,2.36,10614.95,37.78,49687.77,-0.29,8.33
21,21.,UltraTech Cem.,11117.00,39.62,327594.83,0.70,3000.02,20.14,25799.47,11.86,12.78
22,22.,JSW Steel,1297.60,34.86,317322.11,0.55,19243.00,115.02,51180.00,14.19,10.90
23,23.,O N G C,246.20,7.43,309726.47,4.98,13677.87,47.80,173805.19,3.61,14.15
24,24.,HCL Technologies,1109.60,17.34,301108.28,4.87,4490.00,4.20,33981.00,12.35,30.60
25,25.,Bharat Electron,406.50,49.02,297142.51,0.59,2226.35,4.62,10224.43,11.75,36.53
26,NaN,Median: 50 Co.,1319.2,28.32,289200.59,0.88,3400.26,9.51,23337.35,12.28,14.13

In [9]:
df6=pd.read_html('https://www.screener.in/company/NIFTY/')
df6

[    S.No.                 Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %  \
 0      1.  Reliance Industries   1293.00  22.47       1749756.77        0.46
 1      2.            HDFC Bank    772.45  15.64       1189391.41        1.68
 2      3.        Bharti Airtel   1822.50  38.67       1110500.17        0.88
 3      4.           ICICI Bank   1340.80  17.74        961620.51        0.82
 4      5.                  SBI   1017.15  11.27        938892.27        1.71
 5      6.                  TCS   2161.40  14.95        782013.44        2.96
 6      7.        Bajaj Finance    918.30  29.76        571729.38        0.59
 7      8.      Larsen & Toubro   4049.30  33.95        557074.02        0.94
 8      9.       Hind. Unilever   2168.80  33.46        509579.35        1.89
 9     10.              Infosys   1116.40  15.06        452952.05        4.30
 10    11.     Sun Pharma.Inds.   1807.70  34.76        433727.78        0.89
 11    12.            Axis Bank   1356.30  15.99        421816.93        0.07
 12    13.        Maruti Suzuki  13366.00  28.63        420230.48        1.01
 13    14.          Adani Ports   1812.90  32.22        417684.75        0.41
 14    15.      Kotak Mah. Bank    403.30  21.09        401142.71        0.12
 15  S.No.                 Name  CMP  Rs.    P/E  Mar Cap  Rs.Cr.  Div Yld  %
 16    16.        Adani Enterp.   2921.60    NaN        380072.41        0.04
 17    17.                M & M   3042.90  21.40        378393.39        1.08
 18    18.        Titan Company   4184.00  72.15        371449.73        0.26
 19    19.                  ITC    285.10  17.09        357215.14        5.09
 20    20.                 NTPC    353.90  12.69        343165.01        2.36
 21    21.       UltraTech Cem.  11117.00  39.62        327594.83        0.70
 22    22.            JSW Steel   1297.60  34.86        317322.11        0.55
 23    23.              O N G C    246.20   7.43        309726.47        4.98
 24    24.     HCL Technologies   1109.60  17.34        301108.28        4.87
 25    25.      Bharat Electron    406.50  49.02        297142.51        0.59
 26    NaN       Median: 50 Co.    1319.2  28.32        289200.59        0.88

     NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  Qtr Sales Var  %  \
 0         20589.00             -12.55          294059.00             12.50
 1         21074.22               8.05           87182.50              0.46
 2          9247.40             -16.49           55383.20             15.68
 3         15680.64               9.28           49593.75              2.49
 4         20507.98               0.22          131080.12              3.34
 5         13784.00              12.22           70698.00              9.65
 6          5553.30              21.99           21605.79             18.10
 7          6133.06               2.11           82762.16             11.25
 8          2994.00               8.62           16351.00              7.64
 9          8509.00              20.87           46402.00             13.38
 10         2709.66              13.58           14611.79             12.76
 11         7642.08               1.71           34170.99              5.30
 12         3659.00              -6.45           52462.50             28.21
 13         3308.30              11.43           10737.56             26.50
 14         5423.15               4.53           17827.36              6.29
 15  NP Qtr  Rs.Cr.  Qtr Profit Var  %  Sales Qtr  Rs.Cr.  Qtr Sales Var  %
 16         -166.79            -121.16           32439.31             20.30
 17         5259.91              48.85           54981.91             29.07
 18         1179.00              31.00           26920.00             80.48
 19         5469.74               5.30           17824.68             -5.01
 20        10614.95              37.78           49687.77             -0.29
 21         3000.02              20.14           25799.47             11.86
 22        19243.00             115.02           51180.00             14.19
 23        13677.87              47.80          173805.19              3.61
 24         4490.00               4.20           33981.00             12.35
 25         2226.35               4.62           10224.43             11.75
 26         3400.26               9.51           23337.35             12.28

     ROCE  %
 0     10.26
 1      7.04
 2     18.50
 3      7.20
 4      6.13
 5     63.03
 6     10.82
 7     14.57
 8     28.42
 9     39.95
 10    20.53
 11     6.24
 12    19.02
 13    14.12
 14     6.93
 15  ROCE  %
 16     5.80
 17    15.45
 18    25.80
 19    38.93
 20     8.33
 21    12.78
 22    10.90
 23    14.15
 24    30.60
 25    36.53
 26    14.13  ]

In [ ]:
df6[0]
#request,selenium

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1293.00,22.47,1749756.77,0.46,20589.00,-12.55,294059.00,12.50,10.26
1,2.,HDFC Bank,772.45,15.64,1189391.41,1.68,21074.22,8.05,87182.50,0.46,7.04
2,3.,Bharti Airtel,1822.50,38.67,1110500.17,0.88,9247.40,-16.49,55383.20,15.68,18.50
3,4.,ICICI Bank,1340.80,17.74,961620.51,0.82,15680.64,9.28,49593.75,2.49,7.20
4,5.,SBI,1017.15,11.27,938892.27,1.71,20507.98,0.22,131080.12,3.34,6.13
5,6.,TCS,2161.40,14.95,782013.44,2.96,13784.00,12.22,70698.00,9.65,63.03
6,7.,Bajaj Finance,918.30,29.76,571729.38,0.59,5553.30,21.99,21605.79,18.10,10.82
7,8.,Larsen & Toubro,4049.30,33.95,557074.02,0.94,6133.06,2.11,82762.16,11.25,14.57
8,9.,Hind. Unilever,2168.80,33.46,509579.35,1.89,2994.00,8.62,16351.00,7.64,28.42
9,10.,Infosys,1116.40,15.06,452952.05,4.30,8509.00,20.87,46402.00,13.38,39.95
10,11.,Sun Pharma.Inds.,1807.70,34.76,433727.78,0.89,2709.66,13.58,14611.79,12.76,20.53
11,12.,Axis Bank,1356.30,15.99,421816.93,0.07,7642.08,1.71,34170.99,5.30,6.24
12,13.,Maruti Suzuki,13366.00,28.63,420230.48,1.01,3659.00,-6.45,52462.50,28.21,19.02
13,14.,Adani Ports,1812.90,32.22,417684.75,0.41,3308.30,11.43,10737.56,26.50,14.12
14,15.,Kotak Mah. Bank,403.30,21.09,401142.71,0.12,5423.15,4.53,17827.36,6.29,6.93
15,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
16,16.,Adani Enterp.,2921.60,NaN,380072.41,0.04,-166.79,-121.16,32439.31,20.30,5.80
17,17.,M & M,3042.90,21.40,378393.39,1.08,5259.91,48.85,54981.91,29.07,15.45
18,18.,Titan Company,4184.00,72.15,371449.73,0.26,1179.00,31.00,26920.00,80.48,25.80
19,19.,ITC,285.10,17.09,357215.14,5.09,5469.74,5.30,17824.68,-5.01,38.93
20,20.,NTPC,353.90,12.69,343165.01,2.36,10614.95,37.78,49687.77,-0.29,8.33
21,21.,UltraTech Cem.,11117.00,39.62,327594.83,0.70,3000.02,20.14,25799.47,11.86,12.78
22,22.,JSW Steel,1297.60,34.86,317322.11,0.55,19243.00,115.02,51180.00,14.19,10.90
23,23.,O N G C,246.20,7.43,309726.47,4.98,13677.87,47.80,173805.19,3.61,14.15
24,24.,HCL Technologies,1109.60,17.34,301108.28,4.87,4490.00,4.20,33981.00,12.35,30.60
25,25.,Bharat Electron,406.50,49.02,297142.51,0.59,2226.35,4.62,10224.43,11.75,36.53
26,NaN,Median: 50 Co.,1319.2,28.32,289200.59,0.88,3400.26,9.51,23337.35,12.28,14.13

In [22]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [23]:
df7=pd.read_excel('/Users/algo trading 2026/batch 37/11_pandas/e500.xlsx')
df7

,Unnamed: 0,Name,Sector,Price,EPS
0,0,Apple Inc,Information Technology,170.12,9.20
1,1,Abbvie Inc,Health Care,93.29,5.31
2,2,Abbott Laboratories,Health Care,55.28,2.41
3,3,Accenture Plc,Information Technology,145.30,NaN
4,4,Allergan Plc,Health Care,171.81,15.42
...,...,...,...,...,...
97,97,Verizon Communications Inc,Telecommunications,45.85,3.75
98,98,Walgreens Boots Alliance,Consumer Staples,70.25,5.10
99,99,Wells Fargo & Company,Financials,54.02,4.14
100,100,Wal-Mart Stores,Consumer Staples,96.08,4.36
101,101,Exxon Mobil Corp,Energy,80.31,3.56

In [25]:
df4.shape

(102, 4)

In [28]:
list(df4.columns)

['Name', 'Sector', 'Price', 'EPS']

In [29]:
list(df4.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101]

In [32]:
df4.head(10)

                           Name                  Sector    Price    EPS
0                     Apple Inc  Information Technology   170.12   9.20
1                    Abbvie Inc             Health Care    93.29   5.31
2           Abbott Laboratories             Health Care    55.28   2.41
3                 Accenture Plc  Information Technology   145.30    NaN
4                  Allergan Plc             Health Care   171.81  15.42
5  American International Group              Financials    59.50   2.51
6                 Allstate Corp              Financials   100.50   6.79
7                         Amgen             Health Care   168.93  12.58
8               Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
9      American Express Company              Financials    93.92   5.22

In [34]:
df4.tail(8)

                           Name                  Sector   Price   EPS
94                 U.S. Bancorp              Financials   51.88  3.37
95     United Technologies Corp             Industrials  117.05  6.62
96                     Visa Inc  Information Technology  110.27  3.48
97   Verizon Communications Inc      Telecommunications   45.85  3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25  5.10
99        Wells Fargo & Company              Financials   54.02  4.14
100             Wal-Mart Stores        Consumer Staples   96.08  4.36
101            Exxon Mobil Corp                  Energy   80.31  3.56

In [35]:
df4.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    102 non-null    str
 1   Sector  102 non-null    str
 2   Price   102 non-null    float64
 3   EPS     101 non-null    float64
dtypes: float64(2), str(2)
memory usage: 3.3 KB

In [36]:
df4.describe()

             Price        EPS
count   102.000000  101.00000
mean    150.500686    6.49099
std     240.768463    8.62033
min      12.110000    0.02000
25%      54.335000    2.87000
50%      88.295000    4.36000
75%     151.032500    6.62000
max    1762.230000   74.45000

subsetting

In [38]:
df4.EPS

0       9.20
1       5.31
2       2.41
3        NaN
4      15.42
       ...
97      3.75
98      5.10
99      4.14
100     4.36
101     3.56
Name: EPS, Length: 102, dtype: float64

In [41]:
df4['Name']

0                       Apple Inc
1                      Abbvie Inc
2             Abbott Laboratories
3                   Accenture Plc
4                    Allergan Plc
                  ...
97     Verizon Communications Inc
98       Walgreens Boots Alliance
99          Wells Fargo & Company
100               Wal-Mart Stores
101              Exxon Mobil Corp
Name: Name, Length: 102, dtype: str

In [42]:
df4[['Name','Price']]

                           Name   Price
0                     Apple Inc  170.12
1                    Abbvie Inc   93.29
2           Abbott Laboratories   55.28
3                 Accenture Plc  145.30
4                  Allergan Plc  171.81
..                          ...     ...
97   Verizon Communications Inc   45.85
98     Walgreens Boots Alliance   70.25
99        Wells Fargo & Company   54.02
100             Wal-Mart Stores   96.08
101            Exxon Mobil Corp   80.31

[102 rows x 2 columns]

In [48]:
df4[df4['Price']>100]

                               Name                  Sector    Price    EPS
0                         Apple Inc  Information Technology   170.12   9.20
3                     Accenture Plc  Information Technology   145.30    NaN
4                      Allergan Plc             Health Care   171.81  15.42
6                     Allstate Corp              Financials   100.50   6.79
7                             Amgen             Health Care   168.93  12.58
8                   Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
10                   Boeing Company             Industrials   265.04   9.75
12                       Biogen Inc             Health Care   311.92  21.59
14                        Blackrock              Financials   474.05  21.55
16             Berkshire Hath Hld B              Financials   181.27   6.29
18                  Caterpillar Inc             Industrials   137.37   5.55
19                     Celgene Corp             Health Care   102.88   6.40
20             Charter Communicatio  Consumer Discretionary   346.20   1.61
25                 Costco Wholesale        Consumer Staples   171.22   5.82
28                     Chevron Corp                  Energy   114.84   3.57
30              Walt Disney Company  Consumer Discretionary   103.02   5.70
36                     Facebook Inc  Information Technology   179.14   5.19
37                       Fedex Corp             Industrials   217.75  11.91
40            General Dynamics Corp             Industrials   198.70  10.07
44                 Alphabet Class C  Information Technology  1018.48  29.87
45                 Alphabet Class A  Information Technology  1034.09  29.87
46              Goldman Sachs Group              Financials   238.05  19.20
48                       Home Depot  Consumer Discretionary   170.13   6.96
49      Honeywell International Inc             Industrials   148.04   6.95
50  International Business Machines  Information Technology   151.40  13.66
52                Johnson & Johnson             Health Care   138.54   7.14
58             Lockheed Martin Corp             Industrials   312.93  12.72
60                   Mastercard Inc  Information Technology   149.93   4.31
61                  McDonald's Corp  Consumer Discretionary   167.01   6.40
65                       3M Company             Industrials   232.49   8.95
67                 Monsanto Company               Materials   118.19   5.53
71                   Nextera Energy               Utilities   155.70   6.67
75                  Priceline Group  Consumer Discretionary  1762.23  74.45
76                      Pepsico Inc        Consumer Staples   115.50   5.12
79  Philip Morris International Inc        Consumer Staples   103.35   4.49
82                 Raytheon Company             Industrials   184.22   7.56
86             Simon Property Group             Real Estate   159.25   6.05
91           Unitedhealth Group Inc             Health Care   209.75   9.60
92               Union Pacific Corp             Industrials   115.58   5.66
93            United Parcel Service             Industrials   113.20   5.98
95         United Technologies Corp             Industrials   117.05   6.62
96                         Visa Inc  Information Technology   110.27   3.48

In [51]:
df4[df4['EPS']>10]

                               Name                  Sector    Price    EPS
4                      Allergan Plc             Health Care   171.81  15.42
7                             Amgen             Health Care   168.93  12.58
12                       Biogen Inc             Health Care   311.92  21.59
14                        Blackrock              Financials   474.05  21.55
37                       Fedex Corp             Industrials   217.75  11.91
40            General Dynamics Corp             Industrials   198.70  10.07
44                 Alphabet Class C  Information Technology  1018.48  29.87
45                 Alphabet Class A  Information Technology  1034.09  29.87
46              Goldman Sachs Group              Financials   238.05  19.20
50  International Business Machines  Information Technology   151.40  13.66
58             Lockheed Martin Corp             Industrials   312.93  12.72
75                  Priceline Group  Consumer Discretionary  1762.23  74.45

In [54]:
a=df4['EPS']>10
b=df4['Price']>500
df4[a & b]['Name'].to_list()

['Alphabet Class C', 'Alphabet Class A', 'Priceline Group']