In [6]:
import datetime as dt
from zoneinfo import ZoneInfo
new_york_timezone = ZoneInfo('America/New_York')
kolkata_timezone = ZoneInfo('Asia/Kolkata')

print(dt.datetime.now(tz=new_york_timezone))

2026-06-28 07:58:35.631963-04:00

In [5]:
import datetime as dt
print(dt.datetime.now())

2026-06-28 17:27:22.686230

In [7]:
import pandas as pd
df=pd.read_csv('candle1.csv')
df

,Datetime,Close,High,Low,Open,Volume
0,2026-01-26 14:30:00+00:00,442.665009,445.029999,442.130005,445.029999,1121872
1,2026-01-26 14:31:00+00:00,443.399994,443.529999,442.269989,442.665009,268066
2,2026-01-26 14:32:00+00:00,442.079895,443.399994,441.470001,443.364990,292367
3,2026-01-26 14:33:00+00:00,441.380005,442.750000,441.380005,442.029999,213710
4,2026-01-26 14:34:00+00:00,439.649994,441.378387,439.600006,441.378387,389645
...,...,...,...,...,...,...
1930,2026-01-30 20:55:00+00:00,432.059998,432.609985,430.250000,432.609985,496455
1931,2026-01-30 20:56:00+00:00,430.798615,432.100006,430.519989,432.079987,396241
1932,2026-01-30 20:57:00+00:00,430.739990,430.869995,430.399994,430.859985,313633
1933,2026-01-30 20:58:00+00:00,430.600006,430.850006,430.399994,430.750000,353859
1934,2026-01-30 20:59:00+00:00,430.436005,430.920013,430.100006,430.609985,922192

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1935 entries, 0 to 1934
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Datetime  1935 non-null   datetime64[us, UTC]
 1   Close     1935 non-null   float64
 2   High      1935 non-null   float64
 3   Low       1935 non-null   float64
 4   Open      1935 non-null   float64
 5   Volume    1935 non-null   int64
dtypes: datetime64[us, UTC](1), float64(4), int64(1)
memory usage: 90.8 KB

In [9]:
df['Datetime']=pd.to_datetime(df['Datetime'])
df

,Datetime,Close,High,Low,Open,Volume
0,2026-01-26 14:30:00+00:00,442.665009,445.029999,442.130005,445.029999,1121872
1,2026-01-26 14:31:00+00:00,443.399994,443.529999,442.269989,442.665009,268066
2,2026-01-26 14:32:00+00:00,442.079895,443.399994,441.470001,443.364990,292367
3,2026-01-26 14:33:00+00:00,441.380005,442.750000,441.380005,442.029999,213710
4,2026-01-26 14:34:00+00:00,439.649994,441.378387,439.600006,441.378387,389645
...,...,...,...,...,...,...
1930,2026-01-30 20:55:00+00:00,432.059998,432.609985,430.250000,432.609985,496455
1931,2026-01-30 20:56:00+00:00,430.798615,432.100006,430.519989,432.079987,396241
1932,2026-01-30 20:57:00+00:00,430.739990,430.869995,430.399994,430.859985,313633
1933,2026-01-30 20:58:00+00:00,430.600006,430.850006,430.399994,430.750000,353859
1934,2026-01-30 20:59:00+00:00,430.436005,430.920013,430.100006,430.609985,922192

In [19]:
df.set_index('Datetime')

,Close,High,Low,Open,Volume
Datetime,,,,,
2026-01-26 14:30:00+00:00,442.665009,445.029999,442.130005,445.029999,1121872
2026-01-26 14:31:00+00:00,443.399994,443.529999,442.269989,442.665009,268066
2026-01-26 14:32:00+00:00,442.079895,443.399994,441.470001,443.364990,292367
2026-01-26 14:33:00+00:00,441.380005,442.750000,441.380005,442.029999,213710
2026-01-26 14:34:00+00:00,439.649994,441.378387,439.600006,441.378387,389645
...,...,...,...,...,...
2026-01-30 20:55:00+00:00,432.059998,432.609985,430.250000,432.609985,496455
2026-01-30 20:56:00+00:00,430.798615,432.100006,430.519989,432.079987,396241
2026-01-30 20:57:00+00:00,430.739990,430.869995,430.399994,430.859985,313633
2026-01-30 20:58:00+00:00,430.600006,430.850006,430.399994,430.750000,353859
2026-01-30 20:59:00+00:00,430.436005,430.920013,430.100006,430.609985,922192

In [13]:
df['Datetime'].dt.tz_convert("America/New_York")

0      2026-01-26 09:30:00-05:00
1      2026-01-26 09:31:00-05:00
2      2026-01-26 09:32:00-05:00
3      2026-01-26 09:33:00-05:00
4      2026-01-26 09:34:00-05:00
                  ...
1930   2026-01-30 15:55:00-05:00
1931   2026-01-30 15:56:00-05:00
1932   2026-01-30 15:57:00-05:00
1933   2026-01-30 15:58:00-05:00
1934   2026-01-30 15:59:00-05:00
Name: Datetime, Length: 1935, dtype: datetime64[us, America/New_York]

In [14]:
df['Datetime'].dt.tz_convert("America/New_York").dt.tz_localize(None)

0      2026-01-26 09:30:00
1      2026-01-26 09:31:00
2      2026-01-26 09:32:00
3      2026-01-26 09:33:00
4      2026-01-26 09:34:00
               ...
1930   2026-01-30 15:55:00
1931   2026-01-30 15:56:00
1932   2026-01-30 15:57:00
1933   2026-01-30 15:58:00
1934   2026-01-30 15:59:00
Name: Datetime, Length: 1935, dtype: datetime64[us]

In [11]:

df['Datetime'].dt.tz_localize(None)

0      2026-01-26 14:30:00
1      2026-01-26 14:31:00
2      2026-01-26 14:32:00
3      2026-01-26 14:33:00
4      2026-01-26 14:34:00
               ...
1930   2026-01-30 20:55:00
1931   2026-01-30 20:56:00
1932   2026-01-30 20:57:00
1933   2026-01-30 20:58:00
1934   2026-01-30 20:59:00
Name: Datetime, Length: 1935, dtype: datetime64[us]

0      2026-01-26 09:30:00-05:00
1      2026-01-26 09:31:00-05:00
2      2026-01-26 09:32:00-05:00
3      2026-01-26 09:33:00-05:00
4      2026-01-26 09:34:00-05:00
                  ...
1930   2026-01-30 15:55:00-05:00
1931   2026-01-30 15:56:00-05:00
1932   2026-01-30 15:57:00-05:00
1933   2026-01-30 15:58:00-05:00
1934   2026-01-30 15:59:00-05:00
Name: Datetime, Length: 1935, dtype: datetime64[us, America/New_York]

In [15]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-1.4.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (2.34.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (4.10.0)
Collecting pytz>=2022.5 (from yfinance)
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.1.0-py3-none-any.whl.metadata (10 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.15 (from yfinance)
  Using cached curl_cffi-0.15.0-cp310-abi3-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.35.1-cp310-abi3-macosx_10_9_universal2.whl.metadata (595 bytes)
Collecting websockets>=13.0 (from yfinance)
  Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yfinance)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Collecting cffi>=2.0.0 (from curl_cffi>=0.15->yfinance)
  Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.6 kB)
Requirement already satisfied: certifi>=2024.2.2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Collecting rich (from curl_cffi>=0.15->yfinance)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting pycparser (from cffi>=2.0.0->curl_cffi>=0.15->yfinance)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.7.0)
Collecting markdown-it-py>=2.2.0 (from rich->curl_cffi>=0.15->yfinance)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 5.4 MB/s  0:00:00 eta 0:00:01
Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl (181 kB)
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.1.0-py3-none-any.whl (155 kB)
Downloading protobuf-7.35.1-cp310-abi3-macosx_10_9_universal2.whl (433 kB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl (175 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, soupsieve, pycparser, protobuf, mdurl, markdown-it-py, cffi, beautifulsoup4, rich, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/14 [yfinance]/14 [rich]own-it-py]
Successfully installed beautifulsoup4-4.15.0 cffi-2.0.0 curl_cffi-0.15.0 markdown-it-py-4.2.0 mdurl-0.1.2 multitasking-0.0.13 peewee-4.1.0 protobuf-7.35.1 pycparser-3.0 pytz-2026.2 rich-15.0.0 soupsieve-2.8.4 websockets-16.0 yfinance-1.4.1

In [30]:
import yfinance as yf
data=yf.download('TSLA',period='39d',interval='15m',multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2026-05-01 09:30:00-04:00,381.369995,387.399902,378.910004,382.475006,5628401
2026-05-01 09:45:00-04:00,382.945007,383.829987,379.619995,381.390015,2859711
2026-05-01 10:00:00-04:00,386.299988,386.980011,382.500000,382.920013,3102952
2026-05-01 10:15:00-04:00,388.095001,388.419891,384.290009,386.290009,2827583
2026-05-01 10:30:00-04:00,388.355011,389.570007,385.019989,388.095001,3514232
...,...,...,...,...,...
2026-06-26 14:45:00-04:00,379.829987,380.910004,379.049988,380.720001,1238742
2026-06-26 15:00:00-04:00,380.820007,380.820007,379.420105,379.880005,1017814
2026-06-26 15:15:00-04:00,379.760010,380.869995,379.654999,380.809998,737870
2026-06-26 15:30:00-04:00,379.110687,380.140015,378.548798,379.809998,999914
2026-06-26 15:45:00-04:00,379.190002,382.959991,379.029999,379.079987,4581604

In [31]:
end=pd.to_datetime('2026-06-01 00:00:00-04:00')
end

Timestamp('2026-06-01 00:00:00-0400', tz='UTC-04:00')

In [32]:
data[data.index<end]['High'].max()

np.float64(453.3999938964844)

In [33]:
import yfinance as yf
import pandas as pd

data = yf.download('TSLA', period='60d', interval='15m', multi_level_index=False)

prev_month = pd.Timestamp.now().to_period('M') - 1
prev_high = data.loc[data.index.to_period('M') == prev_month, 'High'].max()

print(f"{prev_month} high: {prev_high:.2f}")

[*********************100%***********************]  1 of 1 completed

2026-05 high: 453.40

/var/folders/gf/2xw81y_n41x8mbjy1d6lp0540000gn/T/ipykernel_72858/4018187454.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  prev_high = data.loc[data.index.to_period('M') == prev_month, 'High'].max()